default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: ec2-user
  password: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: typing_test_development

test:
  <<: *default
  database: typing_test_test

production:
  <<: *default
  database: typing_test_production
  username: ec2-user
  password: pg
